"""empty message

Revision ID: adaa6fde2695
Revises: c7b71c1ea041
Create Date: 2025-12-16 09:59:04.154918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adaa6fde2695'
down_revision: Union[str, Sequence[str], None] = 'c7b71c1ea041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'odometer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('car', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('car', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('car', 'images_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('car', 'car_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('car', 'car_vin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'car_vin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('car', 'car_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('car', 'images_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('car', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('car', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('car', 'odometer',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
