"""empty message

Revision ID: c7b71c1ea041
Revises: 210bb0f5371a
Create Date: 2025-12-15 18:24:45.775744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b71c1ea041'
down_revision: Union[str, Sequence[str], None] = '210bb0f5371a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('datetime_found', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'datetime_found')
    # ### end Alembic commands ###
